/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tp7.estudiantes.Vistas;

import java.util.HashSet;
import tp7.estudiantes.Clases.Alumno;
import tp7.estudiantes.Clases.Materia;

/**
 *
 * @author luciano.echevarne
 */
public class Inscripcion extends javax.swing.JFrame {
static HashSet <Alumno> alumnos=new HashSet <>();
static HashSet <Materia> materias=new HashSet <>();;
    /**
     * Creates new form Inscripcion
     */
    public Inscripcion() {
        initComponents();
    }

    public HashSet<Materia> getMaterias() {
        return materias;
    }

    public void agregarMateria(Materia m){
        materias.add(m);
    }
    public HashSet<Alumno> getAlumnos() {
        return alumnos;
    }

    public void agregarAlumno(Alumno m){
        alumnos.add(m);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        escritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        BforMaterias = new javax.swing.JMenuItem();
        BformAlumnos = new javax.swing.JMenuItem();
        BforInscripcion = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        Bexit = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        jMenu1.setText("Formularios");

        BforMaterias.setText("Formulario de Materias");
        BforMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BforMateriasActionPerformed(evt);
            }
        });
        jMenu1.add(BforMaterias);

        BformAlumnos.setText("Formulario de Alumnos");
        BformAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BformAlumnosActionPerformed(evt);
            }
        });
        jMenu1.add(BformAlumnos);

        BforInscripcion.setText("Formulario de Inscripcion");
        BforInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BforInscripcionActionPerformed(evt);
            }
        });
        jMenu1.add(BforInscripcion);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");

        Bexit.setText("Salir");
        Bexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BexitActionPerformed(evt);
            }
        });
        jMenu2.add(Bexit);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BexitActionPerformed
    System.exit(0);   
        // TODO add your handling code here:
    }//GEN-LAST:event_BexitActionPerformed

    private void BforMateriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BforMateriasActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioDeMaterias c1=new FormularioDeMaterias();   
        c1.setVisible(true);
        escritorio.add(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_BforMateriasActionPerformed

    private void BformAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BformAlumnosActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioDeAlumnos c1=new FormularioDeAlumnos();   
        c1.setVisible(true);
        escritorio.add(c1);        // TODO add your handling code here:
    }//GEN-LAST:event_BformAlumnosActionPerformed

    private void BforInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BforInscripcionActionPerformed
        escritorio.removeAll();
        escritorio.repaint();
        FormularioDeInscripcion c1=new FormularioDeInscripcion();   
        c1.setVisible(true);
        escritorio.add(c1);
        // TODO add your handling code here:
    }//GEN-LAST:event_BforInscripcionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inscripcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inscripcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Bexit;
    private javax.swing.JMenuItem BforInscripcion;
    private javax.swing.JMenuItem BforMaterias;
    private javax.swing.JMenuItem BformAlumnos;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
